@startuml
set separator none
title Módulo Shared

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("SpringBootClientRopApplication.SpringBootClientRopApplication_boundary", "SpringBootClientRopApplication", $tags="") {
  Component(SpringBootClientRopApplication.SpringBootClientRopApplication.MóduloShared, "Módulo Shared", $techn="Module", $descr="", $tags="", $link="")
}


SHOW_LEGEND(true)
@enduml